export const mainStyles = {
  appFontRegular: "suzukiRegular",
  appFontBold: "suzukiBold",
  ratingFontSize: 20,
  pageHeadingFont: 24,
  CardImageSize: 80,
  RatingFont: 22,
  h1FontSize: 21,
  h2FontSize: 16,
  h3FontSize: 14,
  h4FontSize: 11,
  tabsIconSize: 30,
  arrowIconSize: 15,
  buttonIconSize: 13,
  borderRadius: 5,
};
